# Created by and for Qt Creator This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

#TARGET = bitwin24

HEADERS = \
   $$PWD/autom4te.cache/traces.2 \
   $$PWD/share/ui.rc \
   $$PWD/src/compat/sanity.h \
   $$PWD/src/config/bitwin24-config.h \
   $$PWD/src/config/bitwin24-config.h.in \
   $$PWD/src/crypto/common.h \
   $$PWD/src/crypto/hmac_sha256.h \
   $$PWD/src/crypto/hmac_sha512.h \
   $$PWD/src/crypto/rfc6979_hmac_sha256.h \
   $$PWD/src/crypto/ripemd160.h \
   $$PWD/src/crypto/scrypt.h \
   $$PWD/src/crypto/sha1.h \
   $$PWD/src/crypto/sha256.h \
   $$PWD/src/crypto/sha512.h \
   $$PWD/src/crypto/sph_blake.h \
   $$PWD/src/crypto/sph_bmw.h \
   $$PWD/src/crypto/sph_cubehash.h \
   $$PWD/src/crypto/sph_echo.h \
   $$PWD/src/crypto/sph_groestl.h \
   $$PWD/src/crypto/sph_jh.h \
   $$PWD/src/crypto/sph_keccak.h \
   $$PWD/src/crypto/sph_luffa.h \
   $$PWD/src/crypto/sph_shavite.h \
   $$PWD/src/crypto/sph_simd.h \
   $$PWD/src/crypto/sph_skein.h \
   $$PWD/src/crypto/sph_types.h \
   $$PWD/src/leveldb/db/builder.h \
   $$PWD/src/leveldb/db/db_impl.h \
   $$PWD/src/leveldb/db/db_iter.h \
   $$PWD/src/leveldb/db/dbformat.h \
   $$PWD/src/leveldb/db/filename.h \
   $$PWD/src/leveldb/db/log_format.h \
   $$PWD/src/leveldb/db/log_reader.h \
   $$PWD/src/leveldb/db/log_writer.h \
   $$PWD/src/leveldb/db/memtable.h \
   $$PWD/src/leveldb/db/skiplist.h \
   $$PWD/src/leveldb/db/snapshot.h \
   $$PWD/src/leveldb/db/table_cache.h \
   $$PWD/src/leveldb/db/version_edit.h \
   $$PWD/src/leveldb/db/version_set.h \
   $$PWD/src/leveldb/db/write_batch_internal.h \
   $$PWD/src/leveldb/helpers/memenv/memenv.h \
   $$PWD/src/leveldb/include/leveldb/c.h \
   $$PWD/src/leveldb/include/leveldb/cache.h \
   $$PWD/src/leveldb/include/leveldb/comparator.h \
   $$PWD/src/leveldb/include/leveldb/db.h \
   $$PWD/src/leveldb/include/leveldb/dumpfile.h \
   $$PWD/src/leveldb/include/leveldb/env.h \
   $$PWD/src/leveldb/include/leveldb/filter_policy.h \
   $$PWD/src/leveldb/include/leveldb/iterator.h \
   $$PWD/src/leveldb/include/leveldb/options.h \
   $$PWD/src/leveldb/include/leveldb/slice.h \
   $$PWD/src/leveldb/include/leveldb/status.h \
   $$PWD/src/leveldb/include/leveldb/table.h \
   $$PWD/src/leveldb/include/leveldb/table_builder.h \
   $$PWD/src/leveldb/include/leveldb/write_batch.h \
   $$PWD/src/leveldb/port/win/stdint.h \
   $$PWD/src/leveldb/port/atomic_pointer.h \
   $$PWD/src/leveldb/port/port.h \
   $$PWD/src/leveldb/port/port_example.h \
   $$PWD/src/leveldb/port/port_posix.h \
   $$PWD/src/leveldb/port/port_win.h \
   $$PWD/src/leveldb/port/thread_annotations.h \
   $$PWD/src/leveldb/table/block.h \
   $$PWD/src/leveldb/table/block_builder.h \
   $$PWD/src/leveldb/table/filter_block.h \
   $$PWD/src/leveldb/table/format.h \
   $$PWD/src/leveldb/table/iterator_wrapper.h \
   $$PWD/src/leveldb/table/merger.h \
   $$PWD/src/leveldb/table/two_level_iterator.h \
   $$PWD/src/leveldb/util/arena.h \
   $$PWD/src/leveldb/util/coding.h \
   $$PWD/src/leveldb/util/crc32c.h \
   $$PWD/src/leveldb/util/env_posix_test_helper.h \
   $$PWD/src/leveldb/util/hash.h \
   $$PWD/src/leveldb/util/histogram.h \
   $$PWD/src/leveldb/util/logging.h \
   $$PWD/src/leveldb/util/mutexlock.h \
   $$PWD/src/leveldb/util/posix_logger.h \
   $$PWD/src/leveldb/util/random.h \
   $$PWD/src/leveldb/util/testharness.h \
   $$PWD/src/leveldb/util/testutil.h \
   $$PWD/src/libzerocoin/Accumulator.h \
   $$PWD/src/libzerocoin/AccumulatorProofOfKnowledge.h \
   $$PWD/src/libzerocoin/bignum.h \
   $$PWD/src/libzerocoin/Coin.h \
   $$PWD/src/libzerocoin/CoinSpend.h \
   $$PWD/src/libzerocoin/Commitment.h \
   $$PWD/src/libzerocoin/Denominations.h \
   $$PWD/src/libzerocoin/ParamGeneration.h \
   $$PWD/src/libzerocoin/Params.h \
   $$PWD/src/libzerocoin/SerialNumberSignatureOfKnowledge.h \
   $$PWD/src/libzerocoin/SpendType.h \
   $$PWD/src/libzerocoin/ZerocoinDefines.h \
   $$PWD/src/obj/build.h \
   $$PWD/src/primitives/block.h \
   $$PWD/src/primitives/deterministicmint.h \
   $$PWD/src/primitives/transaction.h \
   $$PWD/src/primitives/zerocoin.h \
   $$PWD/src/qt/forms/ui_addressbookpage.h \
   $$PWD/src/qt/forms/ui_askpassphrasedialog.h \
   $$PWD/src/qt/forms/ui_bip38tooldialog.h \
   $$PWD/src/qt/forms/ui_blockexplorer.h \
   $$PWD/src/qt/forms/ui_coincontroldialog.h \
   $$PWD/src/qt/forms/ui_editaddressdialog.h \
   $$PWD/src/qt/forms/ui_helpmessagedialog.h \
   $$PWD/src/qt/forms/ui_intro.h \
   $$PWD/src/qt/forms/ui_masternodelist.h \
   $$PWD/src/qt/forms/ui_merchantdialog.h \
   $$PWD/src/qt/forms/ui_multisenddialog.h \
   $$PWD/src/qt/forms/ui_multisigdialog.h \
   $$PWD/src/qt/forms/ui_obfuscationconfig.h \
   $$PWD/src/qt/forms/ui_openuridialog.h \
   $$PWD/src/qt/forms/ui_optionsdialog.h \
   $$PWD/src/qt/forms/ui_overviewpage.h \
   $$PWD/src/qt/forms/ui_privacydialog.h \
   $$PWD/src/qt/forms/ui_receivecoinsdialog.h \
   $$PWD/src/qt/forms/ui_receiverequestdialog.h \
   $$PWD/src/qt/forms/ui_rpcconsole.h \
   $$PWD/src/qt/forms/ui_sendcoinsdialog.h \
   $$PWD/src/qt/forms/ui_sendcoinsentry.h \
   $$PWD/src/qt/forms/ui_signverifymessagedialog.h \
   $$PWD/src/qt/forms/ui_transactiondescdialog.h \
   $$PWD/src/qt/forms/ui_zbwicontroldialog.h \
   $$PWD/src/qt/res/bitwin24-qt-res.rc \
   $$PWD/src/qt/test/paymentrequestdata.h \
   $$PWD/src/qt/test/paymentservertests.h \
   $$PWD/src/qt/test/uritests.h \
   $$PWD/src/qt/addressbookpage.h \
   $$PWD/src/qt/addresstablemodel.h \
   $$PWD/src/qt/askpassphrasedialog.h \
   $$PWD/src/qt/bantablemodel.h \
   $$PWD/src/qt/bip38tooldialog.h \
   $$PWD/src/qt/bitcoinaddressvalidator.h \
   $$PWD/src/qt/bitcoinamountfield.h \
   $$PWD/src/qt/bitcoingui.h \
   $$PWD/src/qt/bitcoinunits.h \
   $$PWD/src/qt/blockexplorer.h \
   $$PWD/src/qt/clientmodel.h \
   $$PWD/src/qt/coincontroldialog.h \
   $$PWD/src/qt/coincontroltreewidget.h \
   $$PWD/src/qt/csvmodelwriter.h \
   $$PWD/src/qt/editaddressdialog.h \
   $$PWD/src/qt/guiconstants.h \
   $$PWD/src/qt/guiutil.h \
   $$PWD/src/qt/intro.h \
   $$PWD/src/qt/macdockiconhandler.h \
   $$PWD/src/qt/macnotificationhandler.h \
   $$PWD/src/qt/masternodelist.h \
   $$PWD/src/qt/merchantdialog.h \
   $$PWD/src/qt/multisenddialog.h \
   $$PWD/src/qt/multisigdialog.h \
   $$PWD/src/qt/networkstyle.h \
   $$PWD/src/qt/notificator.h \
   $$PWD/src/qt/obfuscationconfig.h \
   $$PWD/src/qt/openuridialog.h \
   $$PWD/src/qt/optionsdialog.h \
   $$PWD/src/qt/optionsmodel.h \
   $$PWD/src/qt/overviewpage.h \
   $$PWD/src/qt/paymentrequest.pb.h \
   $$PWD/src/qt/paymentrequestplus.h \
   $$PWD/src/qt/paymentserver.h \
   $$PWD/src/qt/peertablemodel.h \
   $$PWD/src/qt/platformstyle.h \
   $$PWD/src/qt/privacydialog.h \
   $$PWD/src/qt/qvalidatedlineedit.h \
   $$PWD/src/qt/qvaluecombobox.h \
   $$PWD/src/qt/receivecoinsdialog.h \
   $$PWD/src/qt/receiverequestdialog.h \
   $$PWD/src/qt/recentrequeststablemodel.h \
   $$PWD/src/qt/rpcconsole.h \
   $$PWD/src/qt/sendcoinsdialog.h \
   $$PWD/src/qt/sendcoinsentry.h \
   $$PWD/src/qt/signverifymessagedialog.h \
   $$PWD/src/qt/splashscreen.h \
   $$PWD/src/qt/trafficgraphwidget.h \
   $$PWD/src/qt/transactiondesc.h \
   $$PWD/src/qt/transactiondescdialog.h \
   $$PWD/src/qt/transactionfilterproxy.h \
   $$PWD/src/qt/transactionrecord.h \
   $$PWD/src/qt/transactiontablemodel.h \
   $$PWD/src/qt/transactionview.h \
   $$PWD/src/qt/utilitydialog.h \
   $$PWD/src/qt/walletframe.h \
   $$PWD/src/qt/walletmodel.h \
   $$PWD/src/qt/walletmodeltransaction.h \
   $$PWD/src/qt/walletview.h \
   $$PWD/src/qt/winshutdownmonitor.h \
   $$PWD/src/qt/zbwicontroldialog.h \
   $$PWD/src/rpc/client.h \
   $$PWD/src/rpc/protocol.h \
   $$PWD/src/rpc/server.h \
   $$PWD/src/script/bitcoinconsensus.h \
   $$PWD/src/script/interpreter.h \
   $$PWD/src/script/script.h \
   $$PWD/src/script/script_error.h \
   $$PWD/src/script/sigcache.h \
   $$PWD/src/script/sign.h \
   $$PWD/src/script/standard.h \
   $$PWD/src/secp256k1/autom4te.cache/traces.2 \
   $$PWD/src/secp256k1/contrib/lax_der_parsing.h \
   $$PWD/src/secp256k1/contrib/lax_der_privatekey_parsing.h \
   $$PWD/src/secp256k1/include/secp256k1.h \
   $$PWD/src/secp256k1/include/secp256k1_ecdh.h \
   $$PWD/src/secp256k1/include/secp256k1_recovery.h \
   $$PWD/src/secp256k1/src/java/org_bitcoin_NativeSecp256k1.h \
   $$PWD/src/secp256k1/src/java/org_bitcoin_Secp256k1Context.h \
   $$PWD/src/secp256k1/src/modules/ecdh/main_impl.h \
   $$PWD/src/secp256k1/src/modules/ecdh/tests_impl.h \
   $$PWD/src/secp256k1/src/modules/recovery/main_impl.h \
   $$PWD/src/secp256k1/src/modules/recovery/tests_impl.h \
   $$PWD/src/secp256k1/src/basic-config.h \
   $$PWD/src/secp256k1/src/bench.h \
   $$PWD/src/secp256k1/src/ecdsa.h \
   $$PWD/src/secp256k1/src/ecdsa_impl.h \
   $$PWD/src/secp256k1/src/eckey.h \
   $$PWD/src/secp256k1/src/eckey_impl.h \
   $$PWD/src/secp256k1/src/ecmult.h \
   $$PWD/src/secp256k1/src/ecmult_const.h \
   $$PWD/src/secp256k1/src/ecmult_const_impl.h \
   $$PWD/src/secp256k1/src/ecmult_gen.h \
   $$PWD/src/secp256k1/src/ecmult_gen_impl.h \
   $$PWD/src/secp256k1/src/ecmult_impl.h \
   $$PWD/src/secp256k1/src/ecmult_static_context.h \
   $$PWD/src/secp256k1/src/field.h \
   $$PWD/src/secp256k1/src/field_10x26.h \
   $$PWD/src/secp256k1/src/field_10x26_impl.h \
   $$PWD/src/secp256k1/src/field_5x52.h \
   $$PWD/src/secp256k1/src/field_5x52_asm_impl.h \
   $$PWD/src/secp256k1/src/field_5x52_impl.h \
   $$PWD/src/secp256k1/src/field_5x52_int128_impl.h \
   $$PWD/src/secp256k1/src/field_impl.h \
   $$PWD/src/secp256k1/src/group.h \
   $$PWD/src/secp256k1/src/group_impl.h \
   $$PWD/src/secp256k1/src/hash.h \
   $$PWD/src/secp256k1/src/hash_impl.h \
   $$PWD/src/secp256k1/src/libsecp256k1-config.h \
   $$PWD/src/secp256k1/src/libsecp256k1-config.h.in \
   $$PWD/src/secp256k1/src/num.h \
   $$PWD/src/secp256k1/src/num_gmp.h \
   $$PWD/src/secp256k1/src/num_gmp_impl.h \
   $$PWD/src/secp256k1/src/num_impl.h \
   $$PWD/src/secp256k1/src/scalar.h \
   $$PWD/src/secp256k1/src/scalar_4x64.h \
   $$PWD/src/secp256k1/src/scalar_4x64_impl.h \
   $$PWD/src/secp256k1/src/scalar_8x32.h \
   $$PWD/src/secp256k1/src/scalar_8x32_impl.h \
   $$PWD/src/secp256k1/src/scalar_impl.h \
   $$PWD/src/secp256k1/src/scalar_low.h \
   $$PWD/src/secp256k1/src/scalar_low_impl.h \
   $$PWD/src/secp256k1/src/scratch.h \
   $$PWD/src/secp256k1/src/scratch_impl.h \
   $$PWD/src/secp256k1/src/testrand.h \
   $$PWD/src/secp256k1/src/testrand_impl.h \
   $$PWD/src/secp256k1/src/util.h \
   $$PWD/src/secp256k1/configure.ac \
   $$PWD/src/test/data/alertTests.raw.h \
   $$PWD/src/test/data/base58_encode_decode.json.h \
   $$PWD/src/test/data/base58_keys_invalid.json.h \
   $$PWD/src/test/data/base58_keys_valid.json.h \
   $$PWD/src/test/data/script_invalid.json.h \
   $$PWD/src/test/data/script_valid.json.h \
   $$PWD/src/test/data/sig_canonical.json.h \
   $$PWD/src/test/data/sig_noncanonical.json.h \
   $$PWD/src/test/data/sighash.json.h \
   $$PWD/src/test/data/tx_invalid.json.h \
   $$PWD/src/test/data/tx_valid.json.h \
   $$PWD/src/univalue/autom4te.cache/traces.2 \
   $$PWD/src/univalue/include/univalue.h \
   $$PWD/src/univalue/lib/univalue_escapes.h \
   $$PWD/src/univalue/lib/univalue_utffilter.h \
   $$PWD/src/univalue/univalue-config.h \
   $$PWD/src/zmq/zmqabstractnotifier.h \
   $$PWD/src/zmq/zmqconfig.h \
   $$PWD/src/zmq/zmqnotificationinterface.h \
   $$PWD/src/zmq/zmqpublishnotifier.h \
   $$PWD/src/accumulatorcheckpoints.h \
   $$PWD/src/accumulatorcheckpoints.json.h \
   $$PWD/src/accumulatormap.h \
   $$PWD/src/accumulators.h \
   $$PWD/src/activemasternode.h \
   $$PWD/src/addrman.h \
   $$PWD/src/alert.h \
   $$PWD/src/allocators.h \
   $$PWD/src/amount.h \
   $$PWD/src/base58.h \
   $$PWD/src/bip38.h \
   $$PWD/src/bitwin24-cli-res.rc \
   $$PWD/src/bitwin24-tx-res.rc \
   $$PWD/src/bitwin24d-res.rc \
   $$PWD/src/blocksignature.h \
   $$PWD/src/bloom.h \
   $$PWD/src/chain.h \
   $$PWD/src/chainparams.h \
   $$PWD/src/chainparamsbase.h \
   $$PWD/src/chainparamsseeds.h \
   $$PWD/src/checkpoints.h \
   $$PWD/src/checkqueue.h \
   $$PWD/src/clientversion.h \
   $$PWD/src/coincontrol.h \
   $$PWD/src/coins.h \
   $$PWD/src/compat.h \
   $$PWD/src/compressor.h \
   $$PWD/src/core_io.h \
   $$PWD/src/crypter.h \
   $$PWD/src/db.h \
   $$PWD/src/denomination_functions.h \
   $$PWD/src/hash.h \
   $$PWD/src/httprpc.h \
   $$PWD/src/httpserver.h \
   $$PWD/src/init.h \
   $$PWD/src/invalid.h \
   $$PWD/src/invalid_outpoints.json.h \
   $$PWD/src/invalid_serials.json.h \
   $$PWD/src/kernel.h \
   $$PWD/src/key.h \
   $$PWD/src/keystore.h \
   $$PWD/src/leveldbwrapper.h \
   $$PWD/src/limitedmap.h \
   $$PWD/src/main.h \
   $$PWD/src/masternode-budget.h \
   $$PWD/src/masternode-payments.h \
   $$PWD/src/masternode-sync.h \
   $$PWD/src/masternode.h \
   $$PWD/src/masternodeconfig.h \
   $$PWD/src/masternodeman.h \
   $$PWD/src/merkleblock.h \
   $$PWD/src/miner.h \
   $$PWD/src/mintpool.h \
   $$PWD/src/mruset.h \
   $$PWD/src/net.h \
   $$PWD/src/netbase.h \
   $$PWD/src/noui.h \
   $$PWD/src/obfuscation-relay.h \
   $$PWD/src/obfuscation.h \
   $$PWD/src/pow.h \
   $$PWD/src/protocol.h \
   $$PWD/src/pubkey.h \
   $$PWD/src/random.h \
   $$PWD/src/reverse_iterate.h \
   $$PWD/src/reverselock.h \
   $$PWD/src/scheduler.h \
   $$PWD/src/serialize.h \
   $$PWD/src/spork.h \
   $$PWD/src/sporkdb.h \
   $$PWD/src/stakeinput.h \
   $$PWD/src/staking_accounts_db.h \
   $$PWD/src/streams.h \
   $$PWD/src/swifttx.h \
   $$PWD/src/sync.h \
   $$PWD/src/threadsafety.h \
   $$PWD/src/timedata.h \
   $$PWD/src/tinyformat.h \
   $$PWD/src/torcontrol.h \
   $$PWD/src/txdb.h \
   $$PWD/src/txmempool.h \
   $$PWD/src/ui_interface.h \
   $$PWD/src/uint256.h \
   $$PWD/src/uint512.h \
   $$PWD/src/undo.h \
   $$PWD/src/util.h \
   $$PWD/src/utilmoneystr.h \
   $$PWD/src/utilstrencodings.h \
   $$PWD/src/utiltime.h \
   $$PWD/src/validationinterface.h \
   $$PWD/src/version.h \
   $$PWD/src/wallet.h \
   $$PWD/src/wallet_ismine.h \
   $$PWD/src/walletdb.h \
   $$PWD/src/zbwichain.h \
   $$PWD/src/zbwitracker.h \
   $$PWD/src/zbwiwallet.h \
   $$PWD/configure.ac

SOURCES = \
   $$PWD/autom4te.cache/output.0 \
   $$PWD/autom4te.cache/output.1 \
   $$PWD/autom4te.cache/output.2 \
   $$PWD/autom4te.cache/requests \
   $$PWD/autom4te.cache/traces.0 \
   $$PWD/autom4te.cache/traces.1 \
   $$PWD/BITWIN24-Qt.app/Contents/MacOS/BITWIN24-Qt \
   $$PWD/BITWIN24-Qt.app/Contents/Resources/Base.lproj/InfoPlist.strings \
   $$PWD/BITWIN24-Qt.app/Contents/Resources/bitcoin.icns \
   $$PWD/BITWIN24-Qt.app/Contents/Resources/empty.lproj \
   $$PWD/BITWIN24-Qt.app/Contents/Info.plist \
   $$PWD/BITWIN24-Qt.app/Contents/PkgInfo \
   $$PWD/build-aux/m4/ax_boost_base.m4 \
   $$PWD/build-aux/m4/ax_boost_chrono.m4 \
   $$PWD/build-aux/m4/ax_boost_filesystem.m4 \
   $$PWD/build-aux/m4/ax_boost_program_options.m4 \
   $$PWD/build-aux/m4/ax_boost_system.m4 \
   $$PWD/build-aux/m4/ax_boost_thread.m4 \
   $$PWD/build-aux/m4/ax_boost_unit_test_framework.m4 \
   $$PWD/build-aux/m4/ax_check_compile_flag.m4 \
   $$PWD/build-aux/m4/ax_check_link_flag.m4 \
   $$PWD/build-aux/m4/ax_check_preproc_flag.m4 \
   $$PWD/build-aux/m4/ax_cxx_compile_stdcxx.m4 \
   $$PWD/build-aux/m4/ax_gcc_func_attribute.m4 \
   $$PWD/build-aux/m4/ax_pthread.m4 \
   $$PWD/build-aux/m4/bitcoin_find_bdb48.m4 \
   $$PWD/build-aux/m4/bitcoin_qt.m4 \
   $$PWD/build-aux/m4/bitcoin_subdir_to_include.m4 \
   $$PWD/build-aux/m4/gmp.m4 \
   $$PWD/build-aux/m4/l_atomic.m4 \
   $$PWD/build-aux/m4/libtool.m4 \
   $$PWD/build-aux/m4/ltoptions.m4 \
   $$PWD/build-aux/m4/ltsugar.m4 \
   $$PWD/build-aux/m4/ltversion.m4 \
   $$PWD/build-aux/m4/lt~obsolete.m4 \
   $$PWD/build-aux/compile \
   $$PWD/build-aux/config.guess \
   $$PWD/build-aux/config.sub \
   $$PWD/build-aux/depcomp \
   $$PWD/build-aux/install-sh \
   $$PWD/build-aux/ltmain.sh \
   $$PWD/build-aux/missing \
   $$PWD/build-aux/test-driver \
   $$PWD/contrib/bitrpc/bitrpc.py \
   $$PWD/contrib/bitrpc/README.md \
   $$PWD/contrib/debian/examples/bitwin24x.conf \
   $$PWD/contrib/debian/manpages/bitwin24-qt.1 \
   $$PWD/contrib/debian/manpages/bitwin24.conf.5 \
   $$PWD/contrib/debian/manpages/bitwin24d.1 \
   $$PWD/contrib/debian/patches/README \
   $$PWD/contrib/debian/patches/series \
   $$PWD/contrib/debian/source/format \
   $$PWD/contrib/debian/bitwin24-qt.desktop \
   $$PWD/contrib/debian/bitwin24-qt.install \
   $$PWD/contrib/debian/bitwin24-qt.lintian-overrides \
   $$PWD/contrib/debian/bitwin24-qt.protocol \
   $$PWD/contrib/debian/bitwin24d.bash-completion \
   $$PWD/contrib/debian/bitwin24d.examples \
   $$PWD/contrib/debian/bitwin24d.install \
   $$PWD/contrib/debian/bitwin24d.lintian-overrides \
   $$PWD/contrib/debian/bitwin24d.manpages \
   $$PWD/contrib/debian/changelog \
   $$PWD/contrib/debian/compat \
   $$PWD/contrib/debian/control \
   $$PWD/contrib/debian/copyright \
   $$PWD/contrib/debian/gbp.conf \
   $$PWD/contrib/debian/README.md \
   $$PWD/contrib/debian/rules \
   $$PWD/contrib/debian/watch \
   $$PWD/contrib/devtools/check-doc.py \
   $$PWD/contrib/devtools/fix-copyright-headers.py \
   $$PWD/contrib/devtools/git-subtree-check.sh \
   $$PWD/contrib/devtools/github-merge.py \
   $$PWD/contrib/devtools/lint-whitespace.sh \
   $$PWD/contrib/devtools/logprint-scanner.py \
   $$PWD/contrib/devtools/README.md \
   $$PWD/contrib/devtools/split-debug.sh \
   $$PWD/contrib/devtools/split-debug.sh.in \
   $$PWD/contrib/devtools/symbol-check.py \
   $$PWD/contrib/devtools/update-translations.py \
   $$PWD/contrib/dns_seeder/README.md \
   $$PWD/contrib/dns_seeder/test_seeder.py \
   $$PWD/contrib/fixPNG/fixPNG.sh \
   $$PWD/contrib/fixPNG/README.md \
   $$PWD/contrib/gitian-descriptors/gitian-aarch64.yml \
   $$PWD/contrib/gitian-descriptors/gitian-linux.yml \
   $$PWD/contrib/gitian-descriptors/gitian-osx-signer.yml \
   $$PWD/contrib/gitian-descriptors/gitian-osx.yml \
   $$PWD/contrib/gitian-descriptors/gitian-win-signer.yml \
   $$PWD/contrib/gitian-descriptors/gitian-win.yml \
   $$PWD/contrib/gitian-descriptors/README.md \
   $$PWD/contrib/gitian-keys/temp-key.gpg \
   $$PWD/contrib/init/bitwin24d.conf \
   $$PWD/contrib/init/bitwin24d.init \
   $$PWD/contrib/init/bitwin24d.openrc \
   $$PWD/contrib/init/bitwin24d.openrcconf \
   $$PWD/contrib/init/bitwin24d.service \
   $$PWD/contrib/init/README.md \
   $$PWD/contrib/linearize/example-linearize.cfg \
   $$PWD/contrib/linearize/linearize-data.py \
   $$PWD/contrib/linearize/linearize-hashes.py \
   $$PWD/contrib/linearize/README.md \
   $$PWD/contrib/macdeploy/background.svg \
   $$PWD/contrib/macdeploy/custom_dsstore.py \
   $$PWD/contrib/macdeploy/detached-sig-apply.sh \
   $$PWD/contrib/macdeploy/detached-sig-create.sh \
   $$PWD/contrib/macdeploy/fancy.plist \
   $$PWD/contrib/macdeploy/LICENSE \
   $$PWD/contrib/macdeploy/macdeployqtplus \
   $$PWD/contrib/macdeploy/README.md \
   $$PWD/contrib/qos/README.md \
   $$PWD/contrib/qos/tc.sh \
   $$PWD/contrib/seeds/generate-seeds.py \
   $$PWD/contrib/seeds/makeseeds.py \
   $$PWD/contrib/seeds/README.md \
   $$PWD/contrib/spendfrom/README.md \
   $$PWD/contrib/spendfrom/setup.py \
   $$PWD/contrib/spendfrom/spendfrom.py \
   $$PWD/contrib/test-patches/README.md \
   $$PWD/contrib/testgen/base58.py \
   $$PWD/contrib/testgen/gen_base58_test_vectors.py \
   $$PWD/contrib/testgen/README.md \
   $$PWD/contrib/verifysfbinaries/README.md \
   $$PWD/contrib/verifysfbinaries/verify.sh \
   $$PWD/contrib/zmq/zmq_sub.py \
   $$PWD/contrib/bitwin24-qt.pro \
   $$PWD/contrib/bitwin24d.bash-completion \
   $$PWD/contrib/gitian-build.sh \
   $$PWD/contrib/qt_translations.py \
   $$PWD/contrib/README.md \
   $$PWD/contrib/tidy_datadir.sh \
   $$PWD/depends/builders/darwin.mk \
   $$PWD/depends/builders/default.mk \
   $$PWD/depends/builders/linux.mk \
   $$PWD/depends/hosts/darwin.mk \
   $$PWD/depends/hosts/default.mk \
   $$PWD/depends/hosts/linux.mk \
   $$PWD/depends/hosts/mingw32.mk \
   $$PWD/depends/packages/bdb.mk \
   $$PWD/depends/packages/boost.mk \
   $$PWD/depends/packages/dbus.mk \
   $$PWD/depends/packages/expat.mk \
   $$PWD/depends/packages/fontconfig.mk \
   $$PWD/depends/packages/freetype.mk \
   $$PWD/depends/packages/gmp.mk \
   $$PWD/depends/packages/libevent.mk \
   $$PWD/depends/packages/libICE.mk \
   $$PWD/depends/packages/libSM.mk \
   $$PWD/depends/packages/libX11.mk \
   $$PWD/depends/packages/libXau.mk \
   $$PWD/depends/packages/libxcb.mk \
   $$PWD/depends/packages/libXext.mk \
   $$PWD/depends/packages/miniupnpc.mk \
   $$PWD/depends/packages/native_biplist.mk \
   $$PWD/depends/packages/native_ccache.mk \
   $$PWD/depends/packages/native_cctools.mk \
   $$PWD/depends/packages/native_cdrkit.mk \
   $$PWD/depends/packages/native_ds_store.mk \
   $$PWD/depends/packages/native_libdmg-hfsplus.mk \
   $$PWD/depends/packages/native_mac_alias.mk \
   $$PWD/depends/packages/native_protobuf.mk \
   $$PWD/depends/packages/openssl.mk \
   $$PWD/depends/packages/packages.mk \
   $$PWD/depends/packages/protobuf.mk \
   $$PWD/depends/packages/qrencode.mk \
   $$PWD/depends/packages/qt.mk \
   $$PWD/depends/packages/xcb_proto.mk \
   $$PWD/depends/packages/xextproto.mk \
   $$PWD/depends/packages/xproto.mk \
   $$PWD/depends/packages/xtrans.mk \
   $$PWD/depends/packages/zeromq.mk \
   $$PWD/depends/packages/zlib.mk \
   $$PWD/depends/patches/native_biplist/sorted_list.patch \
   $$PWD/depends/patches/native_cdrkit/cdrkit-deterministic.patch \
   $$PWD/depends/patches/native_mac_alias/python3.patch \
   $$PWD/depends/patches/qt/aarch32-qmake.conf \
   $$PWD/depends/patches/qt/aarch64-qmake.conf \
   $$PWD/depends/patches/qt/fix-xcb-include-order.patch \
   $$PWD/depends/patches/qt/fix_qt_pkgconfig.patch \
   $$PWD/depends/patches/qt/mac-qmake.conf \
   $$PWD/depends/patches/qt/mingw-uuidof.patch \
   $$PWD/depends/patches/qt/pidlist_absolute.patch \
   $$PWD/depends/patches/xextproto/fix_aarch64_build.patch \
   $$PWD/depends/patches/zeromq/0001-fix-build-with-older-mingw64.patch \
   $$PWD/depends/config.guess \
   $$PWD/depends/config.site.in \
   $$PWD/depends/config.sub \
   $$PWD/depends/description.md \
   $$PWD/depends/funcs.mk \
   $$PWD/depends/packages.md \
   $$PWD/depends/README.md \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DAnimation.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DAnimation.framework/Versions/5/Qt3DAnimation \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DAnimation.framework/Versions/Current/Qt3DAnimation \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DCore.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DCore.framework/Versions/5/Qt3DCore \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DCore.framework/Versions/Current/Qt3DCore \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DExtras.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DExtras.framework/Versions/5/Qt3DExtras \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DExtras.framework/Versions/Current/Qt3DExtras \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DInput.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DInput.framework/Versions/5/Qt3DInput \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DInput.framework/Versions/Current/Qt3DInput \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DLogic.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DLogic.framework/Versions/5/Qt3DLogic \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DLogic.framework/Versions/Current/Qt3DLogic \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DQuick.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DQuick.framework/Versions/5/Qt3DQuick \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DQuick.framework/Versions/Current/Qt3DQuick \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DQuickScene2D.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DQuickScene2D.framework/Versions/5/Qt3DQuickScene2D \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DQuickScene2D.framework/Versions/Current/Qt3DQuickScene2D \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DRender.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DRender.framework/Versions/5/Qt3DRender \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/Qt3DRender.framework/Versions/Current/Qt3DRender \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtConcurrent.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtConcurrent.framework/Versions/5/QtConcurrent \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtConcurrent.framework/Versions/Current/QtConcurrent \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtCore.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtCore.framework/Versions/Current/QtCore \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtDBus.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/5/QtDBus \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtDBus.framework/Versions/Current/QtDBus \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtGamepad.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtGamepad.framework/Versions/5/QtGamepad \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtGamepad.framework/Versions/Current/QtGamepad \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtGui.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtGui.framework/Versions/Current/QtGui \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtLocation.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtLocation.framework/Versions/5/QtLocation \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtLocation.framework/Versions/Current/QtLocation \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtNetwork.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/Current/QtNetwork \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtPositioning.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtPositioning.framework/Versions/5/QtPositioning \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtPositioning.framework/Versions/Current/QtPositioning \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtPositioningQuick.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtPositioningQuick.framework/Versions/5/QtPositioningQuick \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtPositioningQuick.framework/Versions/Current/QtPositioningQuick \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtPrintSupport.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtPrintSupport.framework/Versions/Current/QtPrintSupport \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtQml.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtQml.framework/Versions/5/QtQml \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtQml.framework/Versions/Current/QtQml \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtQuick.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtQuick.framework/Versions/5/QtQuick \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtQuick.framework/Versions/Current/QtQuick \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtSerialBus.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtSerialBus.framework/Versions/5/QtSerialBus \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtSerialBus.framework/Versions/Current/QtSerialBus \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtSerialPort.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtSerialPort.framework/Versions/5/QtSerialPort \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtSerialPort.framework/Versions/Current/QtSerialPort \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtSql.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtSql.framework/Versions/5/QtSql \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtSql.framework/Versions/Current/QtSql \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtTextToSpeech.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtTextToSpeech.framework/Versions/5/QtTextToSpeech \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtTextToSpeech.framework/Versions/Current/QtTextToSpeech \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtVirtualKeyboard.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtVirtualKeyboard.framework/Versions/5/QtVirtualKeyboard \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtVirtualKeyboard.framework/Versions/Current/QtVirtualKeyboard \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebChannel.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebChannel.framework/Versions/5/QtWebChannel \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebChannel.framework/Versions/Current/QtWebChannel \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngine.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngine.framework/Versions/5/QtWebEngine \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngine.framework/Versions/Current/QtWebEngine \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/am.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/ar.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/bg.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/bn.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/ca.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/cs.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/da.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/de.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/el.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/en-GB.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/en-US.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/es-419.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/es.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/et.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/fa.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/fi.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/fil.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/fr.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/gu.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/he.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/hi.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/hr.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/hu.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/id.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/it.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/ja.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/kn.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/ko.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/lt.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/lv.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/ml.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/mr.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/ms.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/nb.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/nl.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/pl.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/pt-BR.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/pt-PT.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/ro.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/ru.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/sk.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/sl.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/sr.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/sv.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/sw.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/ta.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/te.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/th.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/tr.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/uk.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/vi.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/zh-CN.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_locales/zh-TW.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/icudtl.dat \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_devtools_resources.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_resources.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_resources_100p.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Resources/qtwebengine_resources_200p.pak \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/QtWebEngineCore \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/Current/QtWebEngineCore \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebSockets.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebSockets.framework/Versions/5/QtWebSockets \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebSockets.framework/Versions/Current/QtWebSockets \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebView.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebView.framework/Versions/5/QtWebView \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWebView.framework/Versions/Current/QtWebView \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWidgets.framework/Resources/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/QtWidgets.framework/Versions/Current/QtWidgets \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libboost_chrono-mt.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libboost_filesystem.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libboost_program_options-mt.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libboost_system.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libboost_thread-mt.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libcrypto.1.0.0.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libdb_cxx-4.8.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libevent-2.1.7.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libevent_pthreads-2.1.7.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libgmp.10.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libminiupnpc.17.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libprotobuf.21.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libqrencode.4.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libssl.1.0.0.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Frameworks/libzmq.5.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/MacOS/BITWIN24-Qt \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/bearer/libqgenericbearer.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/canbus/libqtpassthrucanbus.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/canbus/libqtpeakcanbus.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/canbus/libqttinycanbus.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/canbus/libqtvirtualcanbus.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/gamepads/libdarwingamepad.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/generic/libqtuiotouchplugin.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/geometryloaders/libdefaultgeometryloader.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/geometryloaders/libgltfgeometryloader.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/geoservices/libqtgeoservices_esri.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/geoservices/libqtgeoservices_itemsoverlay.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/geoservices/libqtgeoservices_mapbox.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/geoservices/libqtgeoservices_mapboxgl.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/geoservices/libqtgeoservices_nokia.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/geoservices/libqtgeoservices_osm.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/imageformats/libqgif.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/imageformats/libqicns.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/imageformats/libqico.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/imageformats/libqjpeg.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/imageformats/libqmacheif.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/imageformats/libqmacjp2.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/imageformats/libqtga.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/imageformats/libqtiff.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/imageformats/libqwbmp.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/imageformats/libqwebp.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/platforminputcontexts/libqtvirtualkeyboardplugin.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/platforms/libqcocoa.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/platforms/libqminimal.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/platforms/libqoffscreen.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/platforms/libqwebgl.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/platformthemes/libqxdgdesktopportal.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/printsupport/libcocoaprintersupport.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/renderplugins/libscene2d.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/sceneparsers/libassimpsceneimport.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/sceneparsers/libgltfsceneexport.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/sceneparsers/libgltfsceneimport.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/styles/libqmacstyle.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/texttospeech/libqtexttospeech_speechosx.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/virtualkeyboard/libqtvirtualkeyboard_hangul.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/virtualkeyboard/libqtvirtualkeyboard_openwnn.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/virtualkeyboard/libqtvirtualkeyboard_pinyin.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/virtualkeyboard/libqtvirtualkeyboard_tcime.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/virtualkeyboard/libqtvirtualkeyboard_thai.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/webview/libqtwebview_darwin.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PlugIns/webview/libqtwebview_webengine.dylib \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Resources/Base.lproj/InfoPlist.strings \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Resources/bitcoin.icns \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Resources/empty.lproj \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Resources/qt.conf \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Resources/qt_da.qm \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Resources/qt_de.qm \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Resources/qt_es.qm \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Resources/qt_hu.qm \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Resources/qt_ru.qm \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Resources/qt_uk.qm \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Resources/qt_zh_CN.qm \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Resources/qt_zh_TW.qm \
   $$PWD/dist/BITWIN24-Qt.app/Contents/Info.plist \
   $$PWD/dist/BITWIN24-Qt.app/Contents/PkgInfo \
   $$PWD/doc/gitian-building/create_vm_file_location_size.png \
   $$PWD/doc/gitian-building/create_vm_hard_drive.png \
   $$PWD/doc/gitian-building/create_vm_hard_drive_file_type.png \
   $$PWD/doc/gitian-building/create_vm_memsize.png \
   $$PWD/doc/gitian-building/create_vm_page1.png \
   $$PWD/doc/gitian-building/create_vm_storage_physical_hard_drive.png \
   $$PWD/doc/gitian-building/debian_install_10_configure_clock.png \
   $$PWD/doc/gitian-building/debian_install_11_partition_disks.png \
   $$PWD/doc/gitian-building/debian_install_12_choose_disk.png \
   $$PWD/doc/gitian-building/debian_install_13_partition_scheme.png \
   $$PWD/doc/gitian-building/debian_install_14_finish.png \
   $$PWD/doc/gitian-building/debian_install_15_write_changes.png \
   $$PWD/doc/gitian-building/debian_install_16_choose_a_mirror.png \
   $$PWD/doc/gitian-building/debian_install_17_choose_a_mirror2.png \
   $$PWD/doc/gitian-building/debian_install_18_proxy_settings.png \
   $$PWD/doc/gitian-building/debian_install_19_software_selection.png \
   $$PWD/doc/gitian-building/debian_install_1_boot_menu.png \
   $$PWD/doc/gitian-building/debian_install_20_install_grub.png \
   $$PWD/doc/gitian-building/debian_install_21_finish_installation.png \
   $$PWD/doc/gitian-building/debian_install_2_select_a_language.png \
   $$PWD/doc/gitian-building/debian_install_3_select_location.png \
   $$PWD/doc/gitian-building/debian_install_4_configure_keyboard.png \
   $$PWD/doc/gitian-building/debian_install_5_configure_the_network.png \
   $$PWD/doc/gitian-building/debian_install_6_domain_name.png \
   $$PWD/doc/gitian-building/debian_install_6a_set_up_root_password.png \
   $$PWD/doc/gitian-building/debian_install_7_set_up_user_fullname.png \
   $$PWD/doc/gitian-building/debian_install_8_set_up_username.png \
   $$PWD/doc/gitian-building/debian_install_9_user_password.png \
   $$PWD/doc/gitian-building/network_settings.png \
   $$PWD/doc/gitian-building/port_forwarding_rules.png \
   $$PWD/doc/gitian-building/select_startup_disk.png \
   $$PWD/doc/img/bootstrap1.png \
   $$PWD/doc/img/bootstrap2.png \
   $$PWD/doc/img/bootstrap4.png \
   $$PWD/doc/img/bootstrap5.png \
   $$PWD/doc/release-notes/release-notes-1.0.0.md \
   $$PWD/doc/assets-attribution.md \
   $$PWD/doc/bitcoin_logo_doxygen.png \
   $$PWD/doc/bootstrap.md \
   $$PWD/doc/build-osx.md \
   $$PWD/doc/build-unix.md \
   $$PWD/doc/developer-notes.md \
   $$PWD/doc/dnsseed-policy.md \
   $$PWD/doc/Doxyfile \
   $$PWD/doc/Doxyfile.in \
   $$PWD/doc/files.md \
   $$PWD/doc/gitian-building.md \
   $$PWD/doc/guide-startmany.md \
   $$PWD/doc/init.md \
   $$PWD/doc/masternode-budget.md \
   $$PWD/doc/masternode_conf.md \
   $$PWD/doc/multiwallet-qt.md \
   $$PWD/doc/README.md \
   $$PWD/doc/README_osx.md \
   $$PWD/doc/README_windows.txt \
   $$PWD/doc/release-notes.md \
   $$PWD/doc/release-process.md \
   $$PWD/doc/REST-interface.md \
   $$PWD/doc/swifttx.md \
   $$PWD/doc/tor.md \
   $$PWD/doc/translation_process.md \
   $$PWD/doc/travis-ci.txt \
   $$PWD/doc/unit-tests.md \
   $$PWD/doc/zmq.md \
   $$PWD/qa/pull-tester/rpc-tests.sh \
   $$PWD/qa/pull-tester/run-bitcoin-cli \
   $$PWD/qa/pull-tester/run-bitcoind-for-test.sh \
   $$PWD/qa/pull-tester/run-bitcoind-for-test.sh.in \
   $$PWD/qa/pull-tester/tests-config.sh \
   $$PWD/qa/pull-tester/tests-config.sh.in \
   $$PWD/qa/rpc-tests/python-bitcoinrpc/bitcoinrpc/__init__.py \
   $$PWD/qa/rpc-tests/python-bitcoinrpc/bitcoinrpc/authproxy.py \
   $$PWD/qa/rpc-tests/python-bitcoinrpc/setup.py \
   $$PWD/qa/rpc-tests/bipdersig.py \
   $$PWD/qa/rpc-tests/conflictedbalance.sh \
   $$PWD/qa/rpc-tests/forknotify.py \
   $$PWD/qa/rpc-tests/getblocktemplate_longpoll.py \
   $$PWD/qa/rpc-tests/getblocktemplate_proposals.py \
   $$PWD/qa/rpc-tests/getchaintips.py \
   $$PWD/qa/rpc-tests/httpbasics.py \
   $$PWD/qa/rpc-tests/invalidateblock.py \
   $$PWD/qa/rpc-tests/keypool.py \
   $$PWD/qa/rpc-tests/listtransactions.py \
   $$PWD/qa/rpc-tests/mempool_coinbase_spends.py \
   $$PWD/qa/rpc-tests/mempool_resurrect_test.py \
   $$PWD/qa/rpc-tests/mempool_spendcoinbase.py \
   $$PWD/qa/rpc-tests/netutil.py \
   $$PWD/qa/rpc-tests/proxy_test.py \
   $$PWD/qa/rpc-tests/README.md \
   $$PWD/qa/rpc-tests/receivedby.py \
   $$PWD/qa/rpc-tests/reindex.py \
   $$PWD/qa/rpc-tests/rest.py \
   $$PWD/qa/rpc-tests/rpcbind_test.py \
   $$PWD/qa/rpc-tests/send.sh \
   $$PWD/qa/rpc-tests/smartfees.py \
   $$PWD/qa/rpc-tests/socks5.py \
   $$PWD/qa/rpc-tests/test_framework.py \
   $$PWD/qa/rpc-tests/txn_doublespend.py \
   $$PWD/qa/rpc-tests/util.py \
   $$PWD/qa/rpc-tests/util.sh \
   $$PWD/qa/rpc-tests/wallet.py \
   $$PWD/qa/rpc-tests/walletbackup.py \
   $$PWD/qa/rpc-tests/zapwallettxes.sh \
   $$PWD/qa/rpc-tests/zmq_test.py \
   $$PWD/share/certs/BitcoinFoundation_Apple_Cert.pem \
   $$PWD/share/certs/BitcoinFoundation_Comodo_Cert.pem \
   $$PWD/share/certs/PrivateKeyNotes.md \
   $$PWD/share/pixmaps/addressbook16.bmp \
   $$PWD/share/pixmaps/addressbook16mask.bmp \
   $$PWD/share/pixmaps/addressbook20.bmp \
   $$PWD/share/pixmaps/addressbook20mask.bmp \
   $$PWD/share/pixmaps/bitcoin-bc.ico \
   $$PWD/share/pixmaps/bitcoin.ico \
   $$PWD/share/pixmaps/bitcoin128.png \
   $$PWD/share/pixmaps/bitcoin128.xpm \
   $$PWD/share/pixmaps/bitcoin16.png \
   $$PWD/share/pixmaps/bitcoin16.xpm \
   $$PWD/share/pixmaps/bitcoin256.png \
   $$PWD/share/pixmaps/bitcoin256.xpm \
   $$PWD/share/pixmaps/bitcoin32.png \
   $$PWD/share/pixmaps/bitcoin32.xpm \
   $$PWD/share/pixmaps/bitcoin64.png \
   $$PWD/share/pixmaps/bitcoin64.xpm \
   $$PWD/share/pixmaps/check.ico \
   $$PWD/share/pixmaps/favicon.ico \
   $$PWD/share/pixmaps/nsis-header.bmp \
   $$PWD/share/pixmaps/nsis-wizard.bmp \
   $$PWD/share/pixmaps/send16.bmp \
   $$PWD/share/pixmaps/send16mask.bmp \
   $$PWD/share/pixmaps/send16masknoshadow.bmp \
   $$PWD/share/pixmaps/send20.bmp \
   $$PWD/share/pixmaps/send20mask.bmp \
   $$PWD/share/qt/img/reload.png \
   $$PWD/share/qt/img/reload.xcf \
   $$PWD/share/qt/extract_strings_qt.py \
   $$PWD/share/qt/Info.plist \
   $$PWD/share/qt/Info.plist.in \
   $$PWD/share/qt/make_spinner.py \
   $$PWD/share/qt/make_windows_icon.sh \
   $$PWD/share/qt/protobuf.pri \
   $$PWD/share/genbuild.sh \
   $$PWD/share/setup.nsi \
   $$PWD/share/setup.nsi.in \
   $$PWD/src/compat/glibc_compat.cpp \
   $$PWD/src/compat/glibc_sanity.cpp \
   $$PWD/src/compat/glibcxx_compat.cpp \
   $$PWD/src/compat/glibcxx_sanity.cpp \
   $$PWD/src/compat/strnlen.cpp \
   $$PWD/src/config/stamp-h1 \
   $$PWD/src/crypto/aes_helper.c \
   $$PWD/src/crypto/blake.c \
   $$PWD/src/crypto/bmw.c \
   $$PWD/src/crypto/cubehash.c \
   $$PWD/src/crypto/echo.c \
   $$PWD/src/crypto/groestl.c \
   $$PWD/src/crypto/hmac_sha256.cpp \
   $$PWD/src/crypto/hmac_sha512.cpp \
   $$PWD/src/crypto/jh.c \
   $$PWD/src/crypto/keccak.c \
   $$PWD/src/crypto/libbitcoin_crypto.a \
   $$PWD/src/crypto/luffa.c \
   $$PWD/src/crypto/rfc6979_hmac_sha256.cpp \
   $$PWD/src/crypto/ripemd160.cpp \
   $$PWD/src/crypto/scrypt.cpp \
   $$PWD/src/crypto/sha1.cpp \
   $$PWD/src/crypto/sha256.cpp \
   $$PWD/src/crypto/sha512.cpp \
   $$PWD/src/crypto/shavite.c \
   $$PWD/src/crypto/simd.c \
   $$PWD/src/crypto/skein.c \
   $$PWD/src/leveldb/db/autocompact_test.cc \
   $$PWD/src/leveldb/db/builder.cc \
   $$PWD/src/leveldb/db/c.cc \
   $$PWD/src/leveldb/db/c_test.c \
   $$PWD/src/leveldb/db/corruption_test.cc \
   $$PWD/src/leveldb/db/db_bench.cc \
   $$PWD/src/leveldb/db/db_impl.cc \
   $$PWD/src/leveldb/db/db_iter.cc \
   $$PWD/src/leveldb/db/db_test.cc \
   $$PWD/src/leveldb/db/dbformat.cc \
   $$PWD/src/leveldb/db/dbformat_test.cc \
   $$PWD/src/leveldb/db/dumpfile.cc \
   $$PWD/src/leveldb/db/fault_injection_test.cc \
   $$PWD/src/leveldb/db/filename.cc \
   $$PWD/src/leveldb/db/filename_test.cc \
   $$PWD/src/leveldb/db/leveldbutil.cc \
   $$PWD/src/leveldb/db/log_reader.cc \
   $$PWD/src/leveldb/db/log_test.cc \
   $$PWD/src/leveldb/db/log_writer.cc \
   $$PWD/src/leveldb/db/memtable.cc \
   $$PWD/src/leveldb/db/recovery_test.cc \
   $$PWD/src/leveldb/db/repair.cc \
   $$PWD/src/leveldb/db/skiplist_test.cc \
   $$PWD/src/leveldb/db/table_cache.cc \
   $$PWD/src/leveldb/db/version_edit.cc \
   $$PWD/src/leveldb/db/version_edit_test.cc \
   $$PWD/src/leveldb/db/version_set.cc \
   $$PWD/src/leveldb/db/version_set_test.cc \
   $$PWD/src/leveldb/db/write_batch.cc \
   $$PWD/src/leveldb/db/write_batch_test.cc \
   $$PWD/src/leveldb/doc/bench/db_bench_sqlite3.cc \
   $$PWD/src/leveldb/doc/bench/db_bench_tree_db.cc \
   $$PWD/src/leveldb/doc/benchmark.html \
   $$PWD/src/leveldb/doc/impl.md \
   $$PWD/src/leveldb/doc/index.md \
   $$PWD/src/leveldb/doc/log_format.md \
   $$PWD/src/leveldb/doc/table_format.md \
   $$PWD/src/leveldb/helpers/memenv/memenv.cc \
   $$PWD/src/leveldb/helpers/memenv/memenv_test.cc \
   $$PWD/src/leveldb/issues/issue178_test.cc \
   $$PWD/src/leveldb/issues/issue200_test.cc \
   $$PWD/src/leveldb/port/port_posix.cc \
   $$PWD/src/leveldb/port/port_posix_sse.cc \
   $$PWD/src/leveldb/port/port_win.cc \
   $$PWD/src/leveldb/port/README \
   $$PWD/src/leveldb/table/block.cc \
   $$PWD/src/leveldb/table/block_builder.cc \
   $$PWD/src/leveldb/table/filter_block.cc \
   $$PWD/src/leveldb/table/filter_block_test.cc \
   $$PWD/src/leveldb/table/format.cc \
   $$PWD/src/leveldb/table/iterator.cc \
   $$PWD/src/leveldb/table/merger.cc \
   $$PWD/src/leveldb/table/table.cc \
   $$PWD/src/leveldb/table/table_builder.cc \
   $$PWD/src/leveldb/table/table_test.cc \
   $$PWD/src/leveldb/table/two_level_iterator.cc \
   $$PWD/src/leveldb/util/arena.cc \
   $$PWD/src/leveldb/util/arena_test.cc \
   $$PWD/src/leveldb/util/bloom.cc \
   $$PWD/src/leveldb/util/bloom_test.cc \
   $$PWD/src/leveldb/util/cache.cc \
   $$PWD/src/leveldb/util/cache_test.cc \
   $$PWD/src/leveldb/util/coding.cc \
   $$PWD/src/leveldb/util/coding_test.cc \
   $$PWD/src/leveldb/util/comparator.cc \
   $$PWD/src/leveldb/util/crc32c.cc \
   $$PWD/src/leveldb/util/crc32c_test.cc \
   $$PWD/src/leveldb/util/env.cc \
   $$PWD/src/leveldb/util/env_posix.cc \
   $$PWD/src/leveldb/util/env_posix_test.cc \
   $$PWD/src/leveldb/util/env_test.cc \
   $$PWD/src/leveldb/util/env_win.cc \
   $$PWD/src/leveldb/util/filter_policy.cc \
   $$PWD/src/leveldb/util/hash.cc \
   $$PWD/src/leveldb/util/hash_test.cc \
   $$PWD/src/leveldb/util/histogram.cc \
   $$PWD/src/leveldb/util/logging.cc \
   $$PWD/src/leveldb/util/options.cc \
   $$PWD/src/leveldb/util/status.cc \
   $$PWD/src/leveldb/util/testharness.cc \
   $$PWD/src/leveldb/util/testutil.cc \
   $$PWD/src/leveldb/AUTHORS \
   $$PWD/src/leveldb/build_detect_platform \
   $$PWD/src/leveldb/CONTRIBUTING.md \
   $$PWD/src/leveldb/libleveldb.a \
   $$PWD/src/leveldb/libleveldb_sse42.a \
   $$PWD/src/leveldb/libmemenv.a \
   $$PWD/src/leveldb/LICENSE \
   $$PWD/src/leveldb/NEWS \
   $$PWD/src/leveldb/README.md \
   $$PWD/src/leveldb/TODO \
   $$PWD/src/leveldb/WINDOWS.md \
   $$PWD/src/libzerocoin/documentation/manual/intro.tex \
   $$PWD/src/libzerocoin/documentation/manual/manual.pdf \
   $$PWD/src/libzerocoin/documentation/manual/manual.tex \
   $$PWD/src/libzerocoin/documentation/manual/using.tex \
   $$PWD/src/libzerocoin/documentation/Doxyfile \
   $$PWD/src/libzerocoin/Accumulator.cpp \
   $$PWD/src/libzerocoin/AccumulatorProofOfKnowledge.cpp \
   $$PWD/src/libzerocoin/Coin.cpp \
   $$PWD/src/libzerocoin/CoinSpend.cpp \
   $$PWD/src/libzerocoin/Commitment.cpp \
   $$PWD/src/libzerocoin/Denominations.cpp \
   $$PWD/src/libzerocoin/libbitcoin_zerocoin.a \
   $$PWD/src/libzerocoin/LICENSE \
   $$PWD/src/libzerocoin/paramgen.cpp \
   $$PWD/src/libzerocoin/ParamGeneration.cpp \
   $$PWD/src/libzerocoin/Params.cpp \
   $$PWD/src/libzerocoin/SerialNumberSignatureOfKnowledge.cpp \
   $$PWD/src/libzerocoin/zerocoin.pc.in \
   $$PWD/src/primitives/block.cpp \
   $$PWD/src/primitives/deterministicmint.cpp \
   $$PWD/src/primitives/transaction.cpp \
   $$PWD/src/primitives/zerocoin.cpp \
   $$PWD/src/qt/forms/addressbookpage.ui \
   $$PWD/src/qt/forms/askpassphrasedialog.ui \
   $$PWD/src/qt/forms/bip38tooldialog.ui \
   $$PWD/src/qt/forms/blockexplorer.ui \
   $$PWD/src/qt/forms/coincontroldialog.ui \
   $$PWD/src/qt/forms/editaddressdialog.ui \
   $$PWD/src/qt/forms/helpmessagedialog.ui \
   $$PWD/src/qt/forms/intro.ui \
   $$PWD/src/qt/forms/masternodelist.ui \
   $$PWD/src/qt/forms/merchantdialog.ui \
   $$PWD/src/qt/forms/multisenddialog.ui \
   $$PWD/src/qt/forms/multisigdialog.ui \
   $$PWD/src/qt/forms/obfuscationconfig.ui \
   $$PWD/src/qt/forms/openuridialog.ui \
   $$PWD/src/qt/forms/optionsdialog.ui \
   $$PWD/src/qt/forms/overviewpage.ui \
   $$PWD/src/qt/forms/privacydialog.ui \
   $$PWD/src/qt/forms/receivecoinsdialog.ui \
   $$PWD/src/qt/forms/receiverequestdialog.ui \
   $$PWD/src/qt/forms/rpcconsole.ui \
   $$PWD/src/qt/forms/sendcoinsdialog.ui \
   $$PWD/src/qt/forms/sendcoinsentry.ui \
   $$PWD/src/qt/forms/signverifymessagedialog.ui \
   $$PWD/src/qt/forms/tradingdialog.ui \
   $$PWD/src/qt/forms/transactiondescdialog.ui \
   $$PWD/src/qt/forms/zbwicontroldialog.ui \
   $$PWD/src/qt/locale/bitwin24_bg.qm \
   $$PWD/src/qt/locale/bitwin24_bg.ts \
   $$PWD/src/qt/locale/bitwin24_ca.qm \
   $$PWD/src/qt/locale/bitwin24_ca.ts \
   $$PWD/src/qt/locale/bitwin24_cs.qm \
   $$PWD/src/qt/locale/bitwin24_cs.ts \
   $$PWD/src/qt/locale/bitwin24_da.qm \
   $$PWD/src/qt/locale/bitwin24_da.ts \
   $$PWD/src/qt/locale/bitwin24_de.qm \
   $$PWD/src/qt/locale/bitwin24_de.ts \
   $$PWD/src/qt/locale/bitwin24_en.qm \
   $$PWD/src/qt/locale/bitwin24_en.ts \
   $$PWD/src/qt/locale/bitwin24_en_US.qm \
   $$PWD/src/qt/locale/bitwin24_en_US.ts \
   $$PWD/src/qt/locale/bitwin24_eo.qm \
   $$PWD/src/qt/locale/bitwin24_eo.ts \
   $$PWD/src/qt/locale/bitwin24_es.qm \
   $$PWD/src/qt/locale/bitwin24_es.ts \
   $$PWD/src/qt/locale/bitwin24_es_ES.qm \
   $$PWD/src/qt/locale/bitwin24_es_ES.ts \
   $$PWD/src/qt/locale/bitwin24_fi.qm \
   $$PWD/src/qt/locale/bitwin24_fi.ts \
   $$PWD/src/qt/locale/bitwin24_fr_FR.qm \
   $$PWD/src/qt/locale/bitwin24_fr_FR.ts \
   $$PWD/src/qt/locale/bitwin24_hi_IN.qm \
   $$PWD/src/qt/locale/bitwin24_hi_IN.ts \
   $$PWD/src/qt/locale/bitwin24_hr.qm \
   $$PWD/src/qt/locale/bitwin24_hr.ts \
   $$PWD/src/qt/locale/bitwin24_hr_HR.qm \
   $$PWD/src/qt/locale/bitwin24_hr_HR.ts \
   $$PWD/src/qt/locale/bitwin24_it.qm \
   $$PWD/src/qt/locale/bitwin24_it.ts \
   $$PWD/src/qt/locale/bitwin24_ja.qm \
   $$PWD/src/qt/locale/bitwin24_ja.ts \
   $$PWD/src/qt/locale/bitwin24_ko_KR.qm \
   $$PWD/src/qt/locale/bitwin24_ko_KR.ts \
   $$PWD/src/qt/locale/bitwin24_lt_LT.qm \
   $$PWD/src/qt/locale/bitwin24_lt_LT.ts \
   $$PWD/src/qt/locale/bitwin24_nl.qm \
   $$PWD/src/qt/locale/bitwin24_nl.ts \
   $$PWD/src/qt/locale/bitwin24_pl.qm \
   $$PWD/src/qt/locale/bitwin24_pl.ts \
   $$PWD/src/qt/locale/bitwin24_pt.qm \
   $$PWD/src/qt/locale/bitwin24_pt.ts \
   $$PWD/src/qt/locale/bitwin24_pt_BR.qm \
   $$PWD/src/qt/locale/bitwin24_pt_BR.ts \
   $$PWD/src/qt/locale/bitwin24_ro_RO.qm \
   $$PWD/src/qt/locale/bitwin24_ro_RO.ts \
   $$PWD/src/qt/locale/bitwin24_ru.qm \
   $$PWD/src/qt/locale/bitwin24_ru.ts \
   $$PWD/src/qt/locale/bitwin24_sk.qm \
   $$PWD/src/qt/locale/bitwin24_sk.ts \
   $$PWD/src/qt/locale/bitwin24_sv.qm \
   $$PWD/src/qt/locale/bitwin24_sv.ts \
   $$PWD/src/qt/locale/bitwin24_tr.qm \
   $$PWD/src/qt/locale/bitwin24_tr.ts \
   $$PWD/src/qt/locale/bitwin24_uk.qm \
   $$PWD/src/qt/locale/bitwin24_uk.ts \
   $$PWD/src/qt/locale/bitwin24_vi.qm \
   $$PWD/src/qt/locale/bitwin24_vi.ts \
   $$PWD/src/qt/locale/bitwin24_zh_CN.qm \
   $$PWD/src/qt/locale/bitwin24_zh_CN.ts \
   $$PWD/src/qt/locale/bitwin24_zh_TW.qm \
   $$PWD/src/qt/locale/bitwin24_zh_TW.ts \
   $$PWD/src/qt/res/css/default.css \
   $$PWD/src/qt/res/icons/add.png \
   $$PWD/src/qt/res/icons/address-book.png \
   $$PWD/src/qt/res/icons/automint_active.png \
   $$PWD/src/qt/res/icons/automint_inactive.png \
   $$PWD/src/qt/res/icons/bitcoin.icns \
   $$PWD/src/qt/res/icons/bitcoin.ico \
   $$PWD/src/qt/res/icons/bitcoin.png \
   $$PWD/src/qt/res/icons/bitcoin_testnet.ico \
   $$PWD/src/qt/res/icons/bitcoin_testnet.png \
   $$PWD/src/qt/res/icons/bittrex.png \
   $$PWD/src/qt/res/icons/browse.png \
   $$PWD/src/qt/res/icons/clock1.png \
   $$PWD/src/qt/res/icons/clock2.png \
   $$PWD/src/qt/res/icons/clock3.png \
   $$PWD/src/qt/res/icons/clock4.png \
   $$PWD/src/qt/res/icons/clock5.png \
   $$PWD/src/qt/res/icons/configure.png \
   $$PWD/src/qt/res/icons/connect0_16.png \
   $$PWD/src/qt/res/icons/connect1_16.png \
   $$PWD/src/qt/res/icons/connect2_16.png \
   $$PWD/src/qt/res/icons/connect3_16.png \
   $$PWD/src/qt/res/icons/connect4_16.png \
   $$PWD/src/qt/res/icons/debugwindow.png \
   $$PWD/src/qt/res/icons/edit.png \
   $$PWD/src/qt/res/icons/editcopy.png \
   $$PWD/src/qt/res/icons/editpaste.png \
   $$PWD/src/qt/res/icons/export.png \
   $$PWD/src/qt/res/icons/eye.png \
   $$PWD/src/qt/res/icons/eye_minus.png \
   $$PWD/src/qt/res/icons/eye_plus.png \
   $$PWD/src/qt/res/icons/filesave.png \
   $$PWD/src/qt/res/icons/history.png \
   $$PWD/src/qt/res/icons/import.png \
   $$PWD/src/qt/res/icons/key.png \
   $$PWD/src/qt/res/icons/lock_closed.png \
   $$PWD/src/qt/res/icons/lock_en.png \
   $$PWD/src/qt/res/icons/lock_open.png \
   $$PWD/src/qt/res/icons/masternodes.png \
   $$PWD/src/qt/res/icons/merchant.png \
   $$PWD/src/qt/res/icons/notsynced.png \
   $$PWD/src/qt/res/icons/onion.png \
   $$PWD/src/qt/res/icons/overview.png \
   $$PWD/src/qt/res/icons/privacy.png \
   $$PWD/src/qt/res/icons/qrcode.png \
   $$PWD/src/qt/res/icons/quit.png \
   $$PWD/src/qt/res/icons/receive.png \
   $$PWD/src/qt/res/icons/receive_dark.png \
   $$PWD/src/qt/res/icons/remove.png \
   $$PWD/src/qt/res/icons/send.png \
   $$PWD/src/qt/res/icons/send_dark.png \
   $$PWD/src/qt/res/icons/staking_active.png \
   $$PWD/src/qt/res/icons/staking_inactive.png \
   $$PWD/src/qt/res/icons/synced.png \
   $$PWD/src/qt/res/icons/trade.png \
   $$PWD/src/qt/res/icons/transaction0.png \
   $$PWD/src/qt/res/icons/transaction0_dark.png \
   $$PWD/src/qt/res/icons/transaction2.png \
   $$PWD/src/qt/res/icons/transaction_conflicted.png \
   $$PWD/src/qt/res/icons/tx_inout.png \
   $$PWD/src/qt/res/icons/tx_input.png \
   $$PWD/src/qt/res/icons/tx_mined.png \
   $$PWD/src/qt/res/icons/tx_output.png \
   $$PWD/src/qt/res/icons/unit_bwi.png \
   $$PWD/src/qt/res/icons/unit_mbwi.png \
   $$PWD/src/qt/res/icons/unit_tbwi.png \
   $$PWD/src/qt/res/icons/unit_tmbwi.png \
   $$PWD/src/qt/res/icons/unit_tubwi.png \
   $$PWD/src/qt/res/icons/unit_ubwi.png \
   $$PWD/src/qt/res/images/about.png \
   $$PWD/src/qt/res/images/bitwin24_logo_horizontal.png \
   $$PWD/src/qt/res/images/downArrow_dark.png \
   $$PWD/src/qt/res/images/downArrow_small.png \
   $$PWD/src/qt/res/images/downArrow_small_dark.png \
   $$PWD/src/qt/res/images/leftArrow_small_dark.png \
   $$PWD/src/qt/res/images/merchant.png \
   $$PWD/src/qt/res/images/qtreeview_selected.png \
   $$PWD/src/qt/res/images/rewards.png \
   $$PWD/src/qt/res/images/rightArrow_small_dark.png \
   $$PWD/src/qt/res/images/splash.png \
   $$PWD/src/qt/res/images/splash_testnet.png \
   $$PWD/src/qt/res/images/upArrow_small.png \
   $$PWD/src/qt/res/images/upArrow_small_dark.png \
   $$PWD/src/qt/res/images/walletFrame.png \
   $$PWD/src/qt/res/images/walletFrame_bg.png \
   $$PWD/src/qt/res/movies/spinner-000.png \
   $$PWD/src/qt/res/movies/spinner-001.png \
   $$PWD/src/qt/res/movies/spinner-002.png \
   $$PWD/src/qt/res/movies/spinner-003.png \
   $$PWD/src/qt/res/movies/spinner-004.png \
   $$PWD/src/qt/res/movies/spinner-005.png \
   $$PWD/src/qt/res/movies/spinner-006.png \
   $$PWD/src/qt/res/movies/spinner-007.png \
   $$PWD/src/qt/res/movies/spinner-008.png \
   $$PWD/src/qt/res/movies/spinner-009.png \
   $$PWD/src/qt/res/movies/spinner-010.png \
   $$PWD/src/qt/res/movies/spinner-011.png \
   $$PWD/src/qt/res/movies/spinner-012.png \
   $$PWD/src/qt/res/movies/spinner-013.png \
   $$PWD/src/qt/res/movies/spinner-014.png \
   $$PWD/src/qt/res/movies/spinner-015.png \
   $$PWD/src/qt/res/movies/spinner-016.png \
   $$PWD/src/qt/res/movies/spinner-017.png \
   $$PWD/src/qt/res/movies/spinner-018.png \
   $$PWD/src/qt/res/movies/spinner-019.png \
   $$PWD/src/qt/res/movies/spinner-020.png \
   $$PWD/src/qt/res/movies/spinner-021.png \
   $$PWD/src/qt/res/movies/spinner-022.png \
   $$PWD/src/qt/res/movies/spinner-023.png \
   $$PWD/src/qt/res/movies/spinner-024.png \
   $$PWD/src/qt/res/movies/spinner-025.png \
   $$PWD/src/qt/res/movies/spinner-026.png \
   $$PWD/src/qt/res/movies/spinner-027.png \
   $$PWD/src/qt/res/movies/spinner-028.png \
   $$PWD/src/qt/res/movies/spinner-029.png \
   $$PWD/src/qt/res/movies/spinner-030.png \
   $$PWD/src/qt/res/movies/spinner-031.png \
   $$PWD/src/qt/res/movies/spinner-032.png \
   $$PWD/src/qt/res/movies/spinner-033.png \
   $$PWD/src/qt/res/movies/spinner-034.png \
   $$PWD/src/qt/res/src/bitcoin.svg \
   $$PWD/src/qt/res/src/clock1.svg \
   $$PWD/src/qt/res/src/clock2.svg \
   $$PWD/src/qt/res/src/clock3.svg \
   $$PWD/src/qt/res/src/clock4.svg \
   $$PWD/src/qt/res/src/clock5.svg \
   $$PWD/src/qt/res/src/clock_green.svg \
   $$PWD/src/qt/res/src/inout.svg \
   $$PWD/src/qt/res/src/questionmark.svg \
   $$PWD/src/qt/test/moc_paymentservertests.cpp \
   $$PWD/src/qt/test/moc_uritests.cpp \
   $$PWD/src/qt/test/paymentservertests.cpp \
   $$PWD/src/qt/test/test_bitwin24-qt \
   $$PWD/src/qt/test/test_main.cpp \
   $$PWD/src/qt/test/uritests.cpp \
   $$PWD/src/qt/addressbookpage.cpp \
   $$PWD/src/qt/addresstablemodel.cpp \
   $$PWD/src/qt/askpassphrasedialog.cpp \
   $$PWD/src/qt/bantablemodel.cpp \
   $$PWD/src/qt/bip38tooldialog.cpp \
   $$PWD/src/qt/bitcoinaddressvalidator.cpp \
   $$PWD/src/qt/bitcoinamountfield.cpp \
   $$PWD/src/qt/bitcoinamountfield.moc \
   $$PWD/src/qt/bitcoingui.cpp \
   $$PWD/src/qt/bitcoinunits.cpp \
   $$PWD/src/qt/bitwin24-qt \
   $$PWD/src/qt/bitwin24.cpp \
   $$PWD/src/qt/bitwin24.moc \
   $$PWD/src/qt/bitwin24.qrc \
   $$PWD/src/qt/bitwin24_locale.qrc \
   $$PWD/src/qt/bitwin24strings.cpp \
   $$PWD/src/qt/blockexplorer.cpp \
   $$PWD/src/qt/clientmodel.cpp \
   $$PWD/src/qt/coincontroldialog.cpp \
   $$PWD/src/qt/coincontroltreewidget.cpp \
   $$PWD/src/qt/csvmodelwriter.cpp \
   $$PWD/src/qt/editaddressdialog.cpp \
   $$PWD/src/qt/guiutil.cpp \
   $$PWD/src/qt/intro.cpp \
   $$PWD/src/qt/intro.moc \
   $$PWD/src/qt/libbitcoinqt.a \
   $$PWD/src/qt/macdockiconhandler.mm \
   $$PWD/src/qt/macnotificationhandler.mm \
   $$PWD/src/qt/masternodelist.cpp \
   $$PWD/src/qt/merchantdialog.cpp \
   $$PWD/src/qt/moc_addressbookpage.cpp \
   $$PWD/src/qt/moc_addresstablemodel.cpp \
   $$PWD/src/qt/moc_askpassphrasedialog.cpp \
   $$PWD/src/qt/moc_bantablemodel.cpp \
   $$PWD/src/qt/moc_bip38tooldialog.cpp \
   $$PWD/src/qt/moc_bitcoinaddressvalidator.cpp \
   $$PWD/src/qt/moc_bitcoinamountfield.cpp \
   $$PWD/src/qt/moc_bitcoingui.cpp \
   $$PWD/src/qt/moc_bitcoinunits.cpp \
   $$PWD/src/qt/moc_blockexplorer.cpp \
   $$PWD/src/qt/moc_clientmodel.cpp \
   $$PWD/src/qt/moc_coincontroldialog.cpp \
   $$PWD/src/qt/moc_coincontroltreewidget.cpp \
   $$PWD/src/qt/moc_csvmodelwriter.cpp \
   $$PWD/src/qt/moc_editaddressdialog.cpp \
   $$PWD/src/qt/moc_guiutil.cpp \
   $$PWD/src/qt/moc_intro.cpp \
   $$PWD/src/qt/moc_macdockiconhandler.cpp \
   $$PWD/src/qt/moc_macnotificationhandler.cpp \
   $$PWD/src/qt/moc_masternodelist.cpp \
   $$PWD/src/qt/moc_merchantdialog.cpp \
   $$PWD/src/qt/moc_multisenddialog.cpp \
   $$PWD/src/qt/moc_multisigdialog.cpp \
   $$PWD/src/qt/moc_notificator.cpp \
   $$PWD/src/qt/moc_obfuscationconfig.cpp \
   $$PWD/src/qt/moc_openuridialog.cpp \
   $$PWD/src/qt/moc_optionsdialog.cpp \
   $$PWD/src/qt/moc_optionsmodel.cpp \
   $$PWD/src/qt/moc_overviewpage.cpp \
   $$PWD/src/qt/moc_paymentserver.cpp \
   $$PWD/src/qt/moc_peertablemodel.cpp \
   $$PWD/src/qt/moc_privacydialog.cpp \
   $$PWD/src/qt/moc_qvalidatedlineedit.cpp \
   $$PWD/src/qt/moc_qvaluecombobox.cpp \
   $$PWD/src/qt/moc_receivecoinsdialog.cpp \
   $$PWD/src/qt/moc_receiverequestdialog.cpp \
   $$PWD/src/qt/moc_recentrequeststablemodel.cpp \
   $$PWD/src/qt/moc_rpcconsole.cpp \
   $$PWD/src/qt/moc_sendcoinsdialog.cpp \
   $$PWD/src/qt/moc_sendcoinsentry.cpp \
   $$PWD/src/qt/moc_signverifymessagedialog.cpp \
   $$PWD/src/qt/moc_splashscreen.cpp \
   $$PWD/src/qt/moc_trafficgraphwidget.cpp \
   $$PWD/src/qt/moc_transactiondesc.cpp \
   $$PWD/src/qt/moc_transactiondescdialog.cpp \
   $$PWD/src/qt/moc_transactionfilterproxy.cpp \
   $$PWD/src/qt/moc_transactiontablemodel.cpp \
   $$PWD/src/qt/moc_transactionview.cpp \
   $$PWD/src/qt/moc_utilitydialog.cpp \
   $$PWD/src/qt/moc_walletframe.cpp \
   $$PWD/src/qt/moc_walletmodel.cpp \
   $$PWD/src/qt/moc_walletview.cpp \
   $$PWD/src/qt/moc_zbwicontroldialog.cpp \
   $$PWD/src/qt/multisenddialog.cpp \
   $$PWD/src/qt/multisigdialog.cpp \
   $$PWD/src/qt/networkstyle.cpp \
   $$PWD/src/qt/notificator.cpp \
   $$PWD/src/qt/obfuscationconfig.cpp \
   $$PWD/src/qt/openuridialog.cpp \
   $$PWD/src/qt/optionsdialog.cpp \
   $$PWD/src/qt/optionsmodel.cpp \
   $$PWD/src/qt/overviewpage.cpp \
   $$PWD/src/qt/overviewpage.moc \
   $$PWD/src/qt/paymentrequest.pb.cc \
   $$PWD/src/qt/paymentrequest.proto \
   $$PWD/src/qt/paymentrequestplus.cpp \
   $$PWD/src/qt/paymentserver.cpp \
   $$PWD/src/qt/peertablemodel.cpp \
   $$PWD/src/qt/platformstyle.cpp \
   $$PWD/src/qt/privacydialog.cpp \
   $$PWD/src/qt/qrc_bitwin24.cpp \
   $$PWD/src/qt/qrc_bitwin24_locale.cpp \
   $$PWD/src/qt/qvalidatedlineedit.cpp \
   $$PWD/src/qt/qvaluecombobox.cpp \
   $$PWD/src/qt/receivecoinsdialog.cpp \
   $$PWD/src/qt/receiverequestdialog.cpp \
   $$PWD/src/qt/recentrequeststablemodel.cpp \
   $$PWD/src/qt/rpcconsole.cpp \
   $$PWD/src/qt/rpcconsole.moc \
   $$PWD/src/qt/sendcoinsdialog.cpp \
   $$PWD/src/qt/sendcoinsentry.cpp \
   $$PWD/src/qt/signverifymessagedialog.cpp \
   $$PWD/src/qt/splashscreen.cpp \
   $$PWD/src/qt/trafficgraphwidget.cpp \
   $$PWD/src/qt/transactiondesc.cpp \
   $$PWD/src/qt/transactiondescdialog.cpp \
   $$PWD/src/qt/transactionfilterproxy.cpp \
   $$PWD/src/qt/transactionrecord.cpp \
   $$PWD/src/qt/transactiontablemodel.cpp \
   $$PWD/src/qt/transactionview.cpp \
   $$PWD/src/qt/utilitydialog.cpp \
   $$PWD/src/qt/walletframe.cpp \
   $$PWD/src/qt/walletmodel.cpp \
   $$PWD/src/qt/walletmodeltransaction.cpp \
   $$PWD/src/qt/walletview.cpp \
   $$PWD/src/qt/winshutdownmonitor.cpp \
   $$PWD/src/qt/zbwicontroldialog.cpp \
   $$PWD/src/rpc/blockchain.cpp \
   $$PWD/src/rpc/budget.cpp \
   $$PWD/src/rpc/client.cpp \
   $$PWD/src/rpc/masternode.cpp \
   $$PWD/src/rpc/mining.cpp \
   $$PWD/src/rpc/misc.cpp \
   $$PWD/src/rpc/net.cpp \
   $$PWD/src/rpc/protocol.cpp \
   $$PWD/src/rpc/rawtransaction.cpp \
   $$PWD/src/rpc/server.cpp \
   $$PWD/src/script/bitcoinconsensus.cpp \
   $$PWD/src/script/interpreter.cpp \
   $$PWD/src/script/script.cpp \
   $$PWD/src/script/script_error.cpp \
   $$PWD/src/script/sigcache.cpp \
   $$PWD/src/script/sign.cpp \
   $$PWD/src/script/standard.cpp \
   $$PWD/src/secp256k1/autom4te.cache/output.0 \
   $$PWD/src/secp256k1/autom4te.cache/output.1 \
   $$PWD/src/secp256k1/autom4te.cache/output.2 \
   $$PWD/src/secp256k1/autom4te.cache/requests \
   $$PWD/src/secp256k1/autom4te.cache/traces.0 \
   $$PWD/src/secp256k1/autom4te.cache/traces.1 \
   $$PWD/src/secp256k1/build-aux/m4/ax_jni_include_dir.m4 \
   $$PWD/src/secp256k1/build-aux/m4/ax_prog_cc_for_build.m4 \
   $$PWD/src/secp256k1/build-aux/m4/bitcoin_secp.m4 \
   $$PWD/src/secp256k1/build-aux/m4/libtool.m4 \
   $$PWD/src/secp256k1/build-aux/m4/ltoptions.m4 \
   $$PWD/src/secp256k1/build-aux/m4/ltsugar.m4 \
   $$PWD/src/secp256k1/build-aux/m4/ltversion.m4 \
   $$PWD/src/secp256k1/build-aux/m4/lt~obsolete.m4 \
   $$PWD/src/secp256k1/build-aux/compile \
   $$PWD/src/secp256k1/build-aux/config.guess \
   $$PWD/src/secp256k1/build-aux/config.sub \
   $$PWD/src/secp256k1/build-aux/depcomp \
   $$PWD/src/secp256k1/build-aux/install-sh \
   $$PWD/src/secp256k1/build-aux/ltmain.sh \
   $$PWD/src/secp256k1/build-aux/missing \
   $$PWD/src/secp256k1/build-aux/test-driver \
   $$PWD/src/secp256k1/contrib/lax_der_parsing.c \
   $$PWD/src/secp256k1/contrib/lax_der_privatekey_parsing.c \
   $$PWD/src/secp256k1/sage/group_prover.sage \
   $$PWD/src/secp256k1/sage/secp256k1.sage \
   $$PWD/src/secp256k1/sage/weierstrass_prover.sage \
   $$PWD/src/secp256k1/src/asm/field_10x26_arm.s \
   $$PWD/src/secp256k1/src/java/org/bitcoin/NativeSecp256k1.java \
   $$PWD/src/secp256k1/src/java/org/bitcoin/NativeSecp256k1Test.java \
   $$PWD/src/secp256k1/src/java/org/bitcoin/NativeSecp256k1Util.java \
   $$PWD/src/secp256k1/src/java/org/bitcoin/Secp256k1Context.java \
   $$PWD/src/secp256k1/src/java/org_bitcoin_NativeSecp256k1.c \
   $$PWD/src/secp256k1/src/java/org_bitcoin_Secp256k1Context.c \
   $$PWD/src/secp256k1/src/bench_ecdh.c \
   $$PWD/src/secp256k1/src/bench_ecmult.c \
   $$PWD/src/secp256k1/src/bench_internal.c \
   $$PWD/src/secp256k1/src/bench_recover.c \
   $$PWD/src/secp256k1/src/bench_sign.c \
   $$PWD/src/secp256k1/src/bench_verify.c \
   $$PWD/src/secp256k1/src/gen_context.c \
   $$PWD/src/secp256k1/src/secp256k1.c \
   $$PWD/src/secp256k1/src/stamp-h1 \
   $$PWD/src/secp256k1/src/tests.c \
   $$PWD/src/secp256k1/src/tests_exhaustive.c \
   $$PWD/src/secp256k1/aclocal.m4 \
   $$PWD/src/secp256k1/autogen.sh \
   $$PWD/src/secp256k1/config.log \
   $$PWD/src/secp256k1/config.status \
   $$PWD/src/secp256k1/configure \
   $$PWD/src/secp256k1/COPYING \
   $$PWD/src/secp256k1/gen_context \
   $$PWD/src/secp256k1/libsecp256k1.pc \
   $$PWD/src/secp256k1/libsecp256k1.pc.in \
   $$PWD/src/secp256k1/libtool \
   $$PWD/src/secp256k1/README.md \
   $$PWD/src/secp256k1/TODO \
   $$PWD/src/test/data/alertTests.raw \
   $$PWD/src/test/data/base58_encode_decode.json \
   $$PWD/src/test/data/base58_keys_invalid.json \
   $$PWD/src/test/data/base58_keys_valid.json \
   $$PWD/src/test/data/bitcoin-util-test.json \
   $$PWD/src/test/data/blanktx.hex \
   $$PWD/src/test/data/README.md \
   $$PWD/src/test/data/script_invalid.json \
   $$PWD/src/test/data/script_valid.json \
   $$PWD/src/test/data/sig_canonical.json \
   $$PWD/src/test/data/sig_noncanonical.json \
   $$PWD/src/test/data/sighash.json \
   $$PWD/src/test/data/tt-delin1-out.hex \
   $$PWD/src/test/data/tt-delout1-out.hex \
   $$PWD/src/test/data/tt-locktime317000-out.hex \
   $$PWD/src/test/data/tx394b54bb.hex \
   $$PWD/src/test/data/tx_invalid.json \
   $$PWD/src/test/data/tx_valid.json \
   $$PWD/src/test/data/txcreate1.hex \
   $$PWD/src/test/data/txcreate2.hex \
   $$PWD/src/test/data/txcreatesign.hex \
   $$PWD/src/test/accounting_tests.cpp \
   $$PWD/src/test/alert_tests.cpp \
   $$PWD/src/test/allocator_tests.cpp \
   $$PWD/src/test/arith_uint256_tests.cpp \
   $$PWD/src/test/base32_tests.cpp \
   $$PWD/src/test/base58_tests.cpp \
   $$PWD/src/test/base64_tests.cpp \
   $$PWD/src/test/bctest.py \
   $$PWD/src/test/benchmark_zerocoin.cpp \
   $$PWD/src/test/bip32_tests.cpp \
   $$PWD/src/test/bitcoin-util-test.py \
   $$PWD/src/test/bloom_tests.cpp \
   $$PWD/src/test/budget_tests.cpp \
   $$PWD/src/test/buildenv.py \
   $$PWD/src/test/buildenv.py.in \
   $$PWD/src/test/checkblock_tests.cpp \
   $$PWD/src/test/Checkpoints_tests.cpp \
   $$PWD/src/test/coins_tests.cpp \
   $$PWD/src/test/compress_tests.cpp \
   $$PWD/src/test/crypto_tests.cpp \
   $$PWD/src/test/DoS_tests.cpp \
   $$PWD/src/test/getarg_tests.cpp \
   $$PWD/src/test/hash_tests.cpp \
   $$PWD/src/test/key_tests.cpp \
   $$PWD/src/test/libzerocoin_tests.cpp \
   $$PWD/src/test/main_tests.cpp \
   $$PWD/src/test/mempool_tests.cpp \
   $$PWD/src/test/miner_tests.cpp \
   $$PWD/src/test/mruset_tests.cpp \
   $$PWD/src/test/multisig_tests.cpp \
   $$PWD/src/test/netbase_tests.cpp \
   $$PWD/src/test/pmt_tests.cpp \
   $$PWD/src/test/README.md \
   $$PWD/src/test/reverselock_tests.cpp \
   $$PWD/src/test/rpc_tests.cpp \
   $$PWD/src/test/rpc_wallet_tests.cpp \
   $$PWD/src/test/sanity_tests.cpp \
   $$PWD/src/test/scheduler_tests.cpp \
   $$PWD/src/test/script_P2SH_tests.cpp \
   $$PWD/src/test/script_tests.cpp \
   $$PWD/src/test/scriptnum_tests.cpp \
   $$PWD/src/test/serialize_tests.cpp \
   $$PWD/src/test/sighash_tests.cpp \
   $$PWD/src/test/sigopcount_tests.cpp \
   $$PWD/src/test/skiplist_tests.cpp \
   $$PWD/src/test/test_bitwin24 \
   $$PWD/src/test/test_bitwin24.cpp \
   $$PWD/src/test/test_zerocoin.cpp \
   $$PWD/src/test/timedata_tests.cpp \
   $$PWD/src/test/torcontrol_tests.cpp \
   $$PWD/src/test/transaction_tests.cpp \
   $$PWD/src/test/tutorial_zerocoin.cpp \
   $$PWD/src/test/uint256_tests.cpp \
   $$PWD/src/test/univalue_tests.cpp \
   $$PWD/src/test/util_tests.cpp \
   $$PWD/src/test/wallet_tests.cpp \
   $$PWD/src/test/zerocoin_denomination_tests.cpp \
   $$PWD/src/test/zerocoin_implementation_tests.cpp \
   $$PWD/src/test/zerocoin_transactions_tests.cpp \
   $$PWD/src/univalue/autom4te.cache/output.0 \
   $$PWD/src/univalue/autom4te.cache/output.1 \
   $$PWD/src/univalue/autom4te.cache/output.2 \
   $$PWD/src/univalue/autom4te.cache/requests \
   $$PWD/src/univalue/autom4te.cache/traces.0 \
   $$PWD/src/univalue/autom4te.cache/traces.1 \
   $$PWD/src/univalue/build-aux/m4/libtool.m4 \
   $$PWD/src/univalue/build-aux/m4/ltoptions.m4 \
   $$PWD/src/univalue/build-aux/m4/ltsugar.m4 \
   $$PWD/src/univalue/build-aux/m4/ltversion.m4 \
   $$PWD/src/univalue/build-aux/m4/lt~obsolete.m4 \
   $$PWD/src/univalue/build-aux/compile \
   $$PWD/src/univalue/build-aux/config.guess \
   $$PWD/src/univalue/build-aux/config.sub \
   $$PWD/src/univalue/build-aux/depcomp \
   $$PWD/src/univalue/build-aux/install-sh \
   $$PWD/src/univalue/build-aux/ltmain.sh \
   $$PWD/src/univalue/build-aux/missing \
   $$PWD/src/univalue/build-aux/test-driver \
   $$PWD/src/univalue/gen/gen.cpp \
   $$PWD/src/univalue/lib/univalue.cpp \
   $$PWD/src/univalue/lib/univalue_read.cpp \
   $$PWD/src/univalue/lib/univalue_write.cpp \
   $$PWD/src/univalue/pc/libunivalue-uninstalled.pc \
   $$PWD/src/univalue/pc/libunivalue-uninstalled.pc.in \
   $$PWD/src/univalue/pc/libunivalue.pc \
   $$PWD/src/univalue/pc/libunivalue.pc.in \
   $$PWD/src/univalue/test/fail1.json \
   $$PWD/src/univalue/test/fail10.json \
   $$PWD/src/univalue/test/fail11.json \
   $$PWD/src/univalue/test/fail12.json \
   $$PWD/src/univalue/test/fail13.json \
   $$PWD/src/univalue/test/fail14.json \
   $$PWD/src/univalue/test/fail15.json \
   $$PWD/src/univalue/test/fail16.json \
   $$PWD/src/univalue/test/fail17.json \
   $$PWD/src/univalue/test/fail18.json \
   $$PWD/src/univalue/test/fail19.json \
   $$PWD/src/univalue/test/fail2.json \
   $$PWD/src/univalue/test/fail20.json \
   $$PWD/src/univalue/test/fail21.json \
   $$PWD/src/univalue/test/fail22.json \
   $$PWD/src/univalue/test/fail23.json \
   $$PWD/src/univalue/test/fail24.json \
   $$PWD/src/univalue/test/fail25.json \
   $$PWD/src/univalue/test/fail26.json \
   $$PWD/src/univalue/test/fail27.json \
   $$PWD/src/univalue/test/fail28.json \
   $$PWD/src/univalue/test/fail29.json \
   $$PWD/src/univalue/test/fail3.json \
   $$PWD/src/univalue/test/fail30.json \
   $$PWD/src/univalue/test/fail31.json \
   $$PWD/src/univalue/test/fail32.json \
   $$PWD/src/univalue/test/fail33.json \
   $$PWD/src/univalue/test/fail34.json \
   $$PWD/src/univalue/test/fail35.json \
   $$PWD/src/univalue/test/fail36.json \
   $$PWD/src/univalue/test/fail37.json \
   $$PWD/src/univalue/test/fail38.json \
   $$PWD/src/univalue/test/fail39.json \
   $$PWD/src/univalue/test/fail4.json \
   $$PWD/src/univalue/test/fail40.json \
   $$PWD/src/univalue/test/fail41.json \
   $$PWD/src/univalue/test/fail42.json \
   $$PWD/src/univalue/test/fail44.json \
   $$PWD/src/univalue/test/fail5.json \
   $$PWD/src/univalue/test/fail6.json \
   $$PWD/src/univalue/test/fail7.json \
   $$PWD/src/univalue/test/fail8.json \
   $$PWD/src/univalue/test/fail9.json \
   $$PWD/src/univalue/test/no_nul.cpp \
   $$PWD/src/univalue/test/object.cpp \
   $$PWD/src/univalue/test/pass1.json \
   $$PWD/src/univalue/test/pass2.json \
   $$PWD/src/univalue/test/pass3.json \
   $$PWD/src/univalue/test/round1.json \
   $$PWD/src/univalue/test/round2.json \
   $$PWD/src/univalue/test/round3.json \
   $$PWD/src/univalue/test/round4.json \
   $$PWD/src/univalue/test/round5.json \
   $$PWD/src/univalue/test/round6.json \
   $$PWD/src/univalue/test/round7.json \
   $$PWD/src/univalue/test/test_json.cpp \
   $$PWD/src/univalue/test/unitester.cpp \
   $$PWD/src/univalue/aclocal.m4 \
   $$PWD/src/univalue/autogen.sh \
   $$PWD/src/univalue/config.log \
   $$PWD/src/univalue/config.status \
   $$PWD/src/univalue/configure \
   $$PWD/src/univalue/configure.ac \
   $$PWD/src/univalue/COPYING \
   $$PWD/src/univalue/libtool \
   $$PWD/src/univalue/README.md \
   $$PWD/src/univalue/stamp-h1 \
   $$PWD/src/univalue/TODO \
   $$PWD/src/univalue/univalue-config.h.in \
   $$PWD/src/zmq/zmqabstractnotifier.cpp \
   $$PWD/src/zmq/zmqnotificationinterface.cpp \
   $$PWD/src/zmq/zmqpublishnotifier.cpp \
   $$PWD/src/accumulatorcheckpoints.cpp \
   $$PWD/src/accumulatormap.cpp \
   $$PWD/src/accumulators.cpp \
   $$PWD/src/activemasternode.cpp \
   $$PWD/src/addrman.cpp \
   $$PWD/src/alert.cpp \
   $$PWD/src/allocators.cpp \
   $$PWD/src/amount.cpp \
   $$PWD/src/base58.cpp \
   $$PWD/src/bip38.cpp \
   $$PWD/src/bitwin24-cli \
   $$PWD/src/bitwin24-cli.cpp \
   $$PWD/src/bitwin24-tx \
   $$PWD/src/bitwin24-tx.cpp \
   $$PWD/src/bitwin24d \
   $$PWD/src/bitwin24d.cpp \
   $$PWD/src/blocksignature.cpp \
   $$PWD/src/bloom.cpp \
   $$PWD/src/chain.cpp \
   $$PWD/src/chainparams.cpp \
   $$PWD/src/chainparamsbase.cpp \
   $$PWD/src/checkpoints.cpp \
   $$PWD/src/clientversion.cpp \
   $$PWD/src/coins.cpp \
   $$PWD/src/compressor.cpp \
   $$PWD/src/core_read.cpp \
   $$PWD/src/core_write.cpp \
   $$PWD/src/crypter.cpp \
   $$PWD/src/db.cpp \
   $$PWD/src/denomination_functions.cpp \
   $$PWD/src/hash.cpp \
   $$PWD/src/httprpc.cpp \
   $$PWD/src/httpserver.cpp \
   $$PWD/src/init.cpp \
   $$PWD/src/invalid.cpp \
   $$PWD/src/kernel.cpp \
   $$PWD/src/key.cpp \
   $$PWD/src/keystore.cpp \
   $$PWD/src/leveldbwrapper.cpp \
   $$PWD/src/libbitcoin_cli.a \
   $$PWD/src/libbitcoin_common.a \
   $$PWD/src/libbitcoin_server.a \
   $$PWD/src/libbitcoin_util.a \
   $$PWD/src/libbitcoin_wallet.a \
   $$PWD/src/libbitcoin_zmq.a \
   $$PWD/src/main.cpp \
   $$PWD/src/masternode-budget.cpp \
   $$PWD/src/masternode-payments.cpp \
   $$PWD/src/masternode-sync.cpp \
   $$PWD/src/masternode.cpp \
   $$PWD/src/masternodeconfig.cpp \
   $$PWD/src/masternodeman.cpp \
   $$PWD/src/merkleblock.cpp \
   $$PWD/src/miner.cpp \
   $$PWD/src/mintpool.cpp \
   $$PWD/src/net.cpp \
   $$PWD/src/netbase.cpp \
   $$PWD/src/noui.cpp \
   $$PWD/src/obfuscation-relay.cpp \
   $$PWD/src/obfuscation.cpp \
   $$PWD/src/pow.cpp \
   $$PWD/src/protocol.cpp \
   $$PWD/src/pubkey.cpp \
   $$PWD/src/random.cpp \
   $$PWD/src/rest.cpp \
   $$PWD/src/rpcdump.cpp \
   $$PWD/src/rpcwallet.cpp \
   $$PWD/src/scheduler.cpp \
   $$PWD/src/spork.cpp \
   $$PWD/src/sporkdb.cpp \
   $$PWD/src/stakeinput.cpp \
   $$PWD/src/staking_accounts_db.cpp \
   $$PWD/src/swifttx.cpp \
   $$PWD/src/sync.cpp \
   $$PWD/src/timedata.cpp \
   $$PWD/src/torcontrol.cpp \
   $$PWD/src/txdb.cpp \
   $$PWD/src/txmempool.cpp \
   $$PWD/src/uint256.cpp \
   $$PWD/src/util.cpp \
   $$PWD/src/utilmoneystr.cpp \
   $$PWD/src/utilstrencodings.cpp \
   $$PWD/src/utiltime.cpp \
   $$PWD/src/validationinterface.cpp \
   $$PWD/src/wallet.cpp \
   $$PWD/src/wallet_ismine.cpp \
   $$PWD/src/walletdb.cpp \
   $$PWD/src/zbwichain.cpp \
   $$PWD/src/zbwitracker.cpp \
   $$PWD/src/zbwiwallet.cpp \
   $$PWD/aclocal.m4 \
   $$PWD/autogen.sh \
   $$PWD/BITWIN24-Qt.temp.dmg \
   $$PWD/config.log \
   $$PWD/config.status \
   $$PWD/configure \
   $$PWD/CONTRIBUTING.md \
   $$PWD/COPYING \
   $$PWD/INSTALL \
   $$PWD/libtool \
   $$PWD/README.md

INCLUDEPATH = \
    $$PWD/src \
    $$PWD/src/compat \
    $$PWD/src/config \
    $$PWD/src/crypto \
    $$PWD/src/leveldb/db \
    $$PWD/src/leveldb/helpers/memenv \
    $$PWD/src/leveldb/include/leveldb \
    $$PWD/src/leveldb/port \
    $$PWD/src/leveldb/port/win \
    $$PWD/src/leveldb/table \
    $$PWD/src/leveldb/util \
    $$PWD/src/libzerocoin \
    $$PWD/src/obj \
    $$PWD/src/primitives \
    $$PWD/src/qt \
    $$PWD/src/qt/forms \
    $$PWD/src/qt/test \
    $$PWD/src/rpc \
    $$PWD/src/script \
    $$PWD/src/secp256k1/contrib \
    $$PWD/src/secp256k1/include \
    $$PWD/src/secp256k1/src \
    $$PWD/src/secp256k1/src/java \
    $$PWD/src/secp256k1/src/modules/ecdh \
    $$PWD/src/secp256k1/src/modules/recovery \
    $$PWD/src/test/data \
    $$PWD/src/univalue \
    $$PWD/src/univalue/include \
    $$PWD/src/univalue/lib \
    $$PWD/src/zmq

#DEFINES = 

